#!/usr/bin/env bash
m_date=161101
while(($m_date<=161131))
do
  mysql -h localhost -P 3326 -uroot -p123456 -e  "CREATE TABLE play_video_1.video_data_$m_date (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,vid bigint(20) unsigned NOT NULL COMMENT '视频id',uid bigint(20) NOT NULL COMMENT '用户uid',time bigint(20) unsigned NOT NULL COMMENT '观看时间点',client_id varchar(25) NOT NULL DEFAULT '' COMMENT '客户端id',device_id varchar(60) NOT NULL DEFAULT '' COMMENT '设备号',version varchar(20) NOT NULL DEFAULT '' COMMENT '版本号',model varchar(40) NOT NULL DEFAULT '' COMMENT '机型',media_time int(10) NOT NULL DEFAULT '0' COMMENT '视频时长',start_time int(10) NOT NULL DEFAULT '0' COMMENT '观看进度条起始时间点',from_source int(10) NOT NULL DEFAULT '0' COMMENT '来源',from_id bigint(20) NOT NULL DEFAULT '0' COMMENT '额外的来源ID',is_live_replay tinyint(3) NOT NULL DEFAULT '0' COMMENT '是否直播回放视频',downstream_rate int(10) NOT NULL DEFAULT '0' COMMENT '拉流下行速率',ip varchar(32) NOT NULL DEFAULT '' COMMENT '客户端ip',continent varchar(40) NOT NULL DEFAULT '' COMMENT '地区',nation varchar(40) NOT NULL DEFAULT '' COMMENT '国家',province varchar(40) NOT NULL DEFAULT '' COMMENT '省份',city varchar(40) NOT NULL DEFAULT '' COMMENT '城市',isp varchar(100) NOT NULL DEFAULT '' COMMENT '运营商',remote_ip varchar(32) NOT NULL DEFAULT '' COMMENT '远程ip,客户端访问的视频资源的ip',remote_continent varchar(40) NOT NULL DEFAULT '' COMMENT '地区',remote_nation varchar(40) NOT NULL DEFAULT '' COMMENT '国家',remote_province varchar(40) NOT NULL DEFAULT '' COMMENT '省份',remote_city varchar(40) NOT NULL DEFAULT '' COMMENT '城市',remote_isp varchar(100) NOT NULL DEFAULT '' COMMENT '运营商',buffer_count varchar(2000) NOT NULL DEFAULT '' COMMENT '缓冲相关计数',buffer_log varchar(2000) NOT NULL DEFAULT '' COMMENT '卡顿缓冲记录',PRIMARY KEY (id)) ENGINE=InnoDB AUTO_INCREMENT=7840570 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;"
  echo $m_date;
  let m_date++;
done

